/*
 * supports a RESTful API for the Libpod library
 *
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/libpod/images/json' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageSearch200Response {
    /// Automated indicates if the image was created by an automated build.
    #[serde(rename = "Automated", skip_serializing_if = "Option::is_none")]
    pub automated: Option<String>,
    /// Description of the image.
    #[serde(rename = "Description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Index is the image index
    #[serde(rename = "Index", skip_serializing_if = "Option::is_none")]
    pub index: Option<String>,
    /// Name is the canonical name of the image
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Official indicates if it's an official image.
    #[serde(rename = "Official", skip_serializing_if = "Option::is_none")]
    pub official: Option<String>,
    /// Stars is the number of stars of the image.
    #[serde(rename = "Stars", skip_serializing_if = "Option::is_none")]
    pub stars: Option<i64>,
    /// Tag is the image tag
    #[serde(rename = "Tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

impl ImageSearch200Response {
    pub fn new() -> ImageSearch200Response {
        ImageSearch200Response {
            automated: None,
            description: None,
            index: None,
            name: None,
            official: None,
            stars: None,
            tag: None,
        }
    }
}
