/*
 * supports a RESTful API for the Libpod library
 *
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/libpod/images/json' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StoreInfo : StoreInfo describes the container storage and its attributes
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreInfo {
    #[serde(rename = "configFile", skip_serializing_if = "Option::is_none")]
    pub config_file: Option<String>,
    #[serde(rename = "containerStore", skip_serializing_if = "Option::is_none")]
    pub container_store: Option<Box<models::ContainerStore>>,
    #[serde(rename = "graphDriverName", skip_serializing_if = "Option::is_none")]
    pub graph_driver_name: Option<String>,
    #[serde(rename = "graphOptions", skip_serializing_if = "Option::is_none")]
    pub graph_options: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "graphRoot", skip_serializing_if = "Option::is_none")]
    pub graph_root: Option<String>,
    /// GraphRootAllocated is how much space the graphroot has in bytes
    #[serde(rename = "graphRootAllocated", skip_serializing_if = "Option::is_none")]
    pub graph_root_allocated: Option<i32>,
    /// GraphRootUsed is how much of graphroot is used in bytes
    #[serde(rename = "graphRootUsed", skip_serializing_if = "Option::is_none")]
    pub graph_root_used: Option<i32>,
    #[serde(rename = "graphStatus", skip_serializing_if = "Option::is_none")]
    pub graph_status: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "imageCopyTmpDir", skip_serializing_if = "Option::is_none")]
    pub image_copy_tmp_dir: Option<String>,
    #[serde(rename = "imageStore", skip_serializing_if = "Option::is_none")]
    pub image_store: Option<Box<models::ImageStore>>,
    #[serde(rename = "runRoot", skip_serializing_if = "Option::is_none")]
    pub run_root: Option<String>,
    #[serde(rename = "transientStore", skip_serializing_if = "Option::is_none")]
    pub transient_store: Option<bool>,
    #[serde(rename = "volumePath", skip_serializing_if = "Option::is_none")]
    pub volume_path: Option<String>,
}

impl StoreInfo {
    /// StoreInfo describes the container storage and its attributes
    pub fn new() -> StoreInfo {
        StoreInfo {
            config_file: None,
            container_store: None,
            graph_driver_name: None,
            graph_options: None,
            graph_root: None,
            graph_root_allocated: None,
            graph_root_used: None,
            graph_status: None,
            image_copy_tmp_dir: None,
            image_store: None,
            run_root: None,
            transient_store: None,
            volume_path: None,
        }
    }
}
