name: Main

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    #- name: Set up Homebrew
    #  uses: Homebrew/actions/setup-homebrew@master

    - name: Remove Podman
      run: |
        sudo apt-get remove crun podman

    - uses: actions/checkout@v4
      with:
        repository: containers/podman
        ref: v5.1.2
        path: ./podman

    - name: Build Podman
      run: |
        cd podman
        make PREFIX=/usr
        sudo make install PREFIX=/usr

    - name: Start Podman
      run: |
        podman --version
        systemctl --user enable --now podman.socket
        systemctl --user status podman.socket

    #- name: Install Podman
    #    brew install crun podman

    #- name: Versions
    #  run: |
    #    crun --version
    #    podman version

    #- name: Start Podman
    #  run: brew services start podman

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-rdme

    - name: Format
      run: cargo fmt --check

    - name: README sync 
      run: cargo rdme --check

    - name: Build
      run: cargo build --verbose

    - name: Tests
      run: cargo test --verbose
